CREATE DATABASE dungeonQuest;
USE dungeonQuest;

CREATE TABLE Questoes(
idQuestao INT PRIMARY KEY auto_increment,
materia VARCHAR (40) NOT NULL,
enunciado VARCHAR(210) NOT NULL,
alternativa_a VARCHAR (60) NOT NULL,
alternativa_b VARCHAR (60) NOT NULL,
alternativa_c VARCHAR (60) NOT NULL,
alternativa_d VARCHAR (60) NOT NULL,
resposta_correta VARCHAR (60) NOT NULL,
justificativa VARCHAR(210) NOT NULL
);

CREATE TABLE Sala(
idSala INT PRIMARY KEY AUTO_INCREMENT,
materia VARCHAR(40) NOT NULL,
tokenSala VARCHAR(6) NOT NULL,
qntdJogadores INT NOT NULL,
levels INT NOT NULL,
donoSala INT NOT NULL UNIQUE
FOREIGN KEY (materia) REFERENCES Questoes(materia)
);

CREATE TABLE Usuario(
idUsuario INT PRIMARY KEY AUTO_INCREMENT,
idSala INT,
loginUsuario VARCHAR(30) NOT NULL UNIQUE,
senhaUsuario VARCHAR(30) NOT NULL
FOREIGN KEY (idSala) REFERENCES Sala(idSala)
);

CREATE TABLE UsuarioSala(
idSala INT NOT NULL,
idUsuario INT
FOREIGN KEY (idUsuario) REFERENCES Usuario(idUsuario)
);
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO questoes (materia, enunciado, alternativa_a, alternativa_b, alternativa_c, alternativa_d, resposta_correta, justificativa)
VALUES
('bd', 'Qual é a função da cláusula FROM em sql?', 'Listar as chaves primarias das tabelas', 'Listar o número de atributos da tabela', 'Listar as tabelas que contêm dados a serem recuperados', 'Listar quantas relações existem no esquema', 'Listar as tabelas que contêm dados a serem recuperados', 'A cláusula FROM lista as tabelas que contêm dados a serem recuperados pela query'),
('bd', 'Um Sistema de Banco de Dados corresponde à união do:', 'Banco de dados com o usuário', 'Banco de dados com as queries', 'Banco de dados com as tabelas', 'Banco de dados com o software DBMS', 'Banco de dados com o software DBMS', 'A união entre um banco de dados com o sofware DBMS é chamado de Sistema de Banco de Dados.'),
('bd', 'Para sequestoes calcular a média de algo no sql se utiliza o comando:', 'SUM', 'AVG', 'INSERT', 'DROP', 'AVG', 'Para se calcular a média é utilizado o comando AVG(o que deseja ser calculado)'),
('bd', 'Quantas fases tem um projeto de banco de dados?', '1', '2', '3', '4', '4', 'Um projeto tem banco de dados contém 4 fases, sendo elas: Especificação e Análise de Requisitos, Projeto Conceitual, Projeto Lógico, Projeto Físico'),
('bd', 'SQL é uma linguagem:', 'Declarativa', 'Funcional', 'Orientada a objetos', 'Procedural', 'Declarativa', 'A linguagem SQL é uma linguagem Procedural'),
('bd', 'No modelo conceitual, uma _____________ representa um objeto ou um conceito do mundo real, como um funcionário ou um projeto do minimundo que é descrito no banco de dados.', 'Entidade', 'Associação', 'Especialização ', 'Transação', 'Entidade', 'No modelo conceitual, uma "entidade" representa um objeto ou um conceito do mundo real, como um funcionário ou um projeto do minimundo que é descrito no banco de dados.'),
('bd', 'No modelo conceitual, um ______________ representa alguma propriedade de interesse que descreve melhor uma entidade, como por exemplo o nome ou o salário de um Funcionário.', 'Relacionamento ', 'Índice', 'Hash', 'Atributo', 'Atributo ', 'No modelo conceitual, um "atributo" representa alguma propriedade de interesse que descreve melhor uma entidade, como por exemplo o nome ou o salário de um funcionário.'),
('bd', 'São exemplos de modelos de dados legados:', 'Hierárquico e Rede', 'Relacional e Hierárquico', 'Relacional e Orientado a Objeto', 'Relacional e Rede ', 'Hierárquico e Rede', 'Hierárquico: Nesse modelo os dados possuem apenas um pai e vários filhos. Rede: O modelo de dados em rede é uma evolução do modelo hierárquico, permitindo que um nó possua vários pais e filhos.'),
('bd', 'Em geral, um esquema de relação pode ter mais de uma chave. Nesse caso, cada uma das chaves é chamada chave:', 'Candidata', 'Estrangeira', 'Múltipla', 'Adaptativas', 'Candidata', 'A alternativa correta é ("candidata") porque, em um esquema de relação, pode haver mais de uma chave possível. Essas chaves adicionais, além da chave primária, são chamadas de chaves candidatas.'),
('bd', 'No modelo conceitual, um relacionamento entre duas ou mais entidades representa uma _______________ entre elas, por exemplo: um funcionário trabalha em um projeto.', 'Segmentação', 'Associação', 'Adaptativas', 'Disjunção', 'Associação', 'É a correta porque, no modelo conceitual, um relacionamento entre duas ou mais entidades é representado por meio de uma associação entre elas.'),
('bd', 'Em geral, um esquema de relação pode ter mais de uma chave. Nesse caso, cada uma das chaves é chamada chave candidata. É comum designar-se uma das chaves candidatas como chave:', 'Primária', 'Estrangeira', 'Principal', 'Forte', 'Primária', 'Porque em um esquema de relação, quando existem mais de uma chave candidata, uma delas é escolhida para ser a chave primária.'),
('bd', 'A chave candidata cujos valores são utilizados para identificar tuplas em uma relação, é conhecida por chave:', 'Únicas', 'Estrangeiras', 'Relacionais', 'Adaptativas.', 'Únicas', 'Quando temos mais de uma chave candidata em uma relação, uma delas é escolhida como a chave primária, que é responsável por identificar exclusivamente cada tupla na relação'),
('bd', 'Um estado de banco de dados que não obedece a todas as restrições de integridade é chamado de estado:', 'Inválido', 'Temporário', 'Contingente', 'Transitório', 'Inválido', ' A alternativa correta é a A ("inválido") porque, quando um estado de banco de dados não está em conformidade com todas as restrições de integridade definidas, ele é considerado inválido.'),
('bd', 'Qual é a principal vantagem de usar um banco de dados relacional?', 'Flexibilidade', 'Velocidade', 'Facilidade de uso', 'Integridade dos dados', 'Integridade dos dados', ' A principal vantagem de usar um banco de dados relacional é a integridade dos dados.'),
('bd', '"A nota de um aluno só pode ir de 0 a 10",essa condição pode ser chamada como regra de:', 'Navathe', 'Tabela', 'Domínio', 'Chave Estrangeira', 'Domínio', 'A regra de domínio é uma condição usada para validar, corrigir e padronizar valores de domínio.'),
('bd', 'Qual é a principal função de uma chave estrangeira em um banco de dados relacional?', 'Tornar a pesquisa mais rapida', 'Garantir a integridade referencial', 'Facilitar o acesso as tabelas', 'Garantir a integridade dos dados ', 'Garantir a integridade referencial', 'A principal função de uma chave estrangeira em um banco de dados relacional é de a garantir a integridade referencial'),
('bd', 'O que é uma query em banco de dados?', 'É um tipo de banco de dados', 'É um tipo de índice', 'É uma chave estrangeira', 'É um comando para manipular dados', 'É um comando para manipular dados', 'Uma query é um comando ou instrução usada para recuperar, inserir, atualizar ou excluir dados em um banco de dados. É uma maneira de interagir com o banco de dados e manipular os dados armazenados nele.'),
('bd', 'Qual é a função do comando SELECT em sql?', 'Inserir dados em uma tabela', 'Excluir dados de uma tabela', 'Extrair dados de uma ou mais tabelas', 'Atualizar dados em uma tabela', 'Extrair dados de uma ou mais tabelas', ' O comando SELECT é utilizado para extrair os dados das tabelas de um banco de dados. Ele pode extrair dados de uma ou mais tabelas ao mesmo tempo.'),
('bd', 'Qual é a principal função de um índice em um banco de dados relacional?', 'Aumentar a velocidade de consulta', 'Reduzir o tamanho do banco de dados', 'Facilitar a inserção de dados', 'Garantir a integridade dos dados ', 'Aumentar a velocidade de consulta', 'A principal função de um índice em um banco de dados relacional é otimizar a tarefa tornando a consulta mais rápida.'),
('bd', 'Existem quantos tipos de restrições entre os relacionamentos?', '1', '4', '2', '7', '2', 'Há 2 tipos de restrições entre relacionamentos de banco de dados: Razão de Cardinalidade e Restrição de Participação'),
('bd', 'São tipos de relacionamento de banco de dados:', 'Recursivo e Binário', 'Ternário e Computacional', 'Ternário e Conceitual', 'Binário e Ocasional', 'Recursivo e Binário', 'Os relacionamentos definem as associações entre as entidades uma associação entre entidades, Recursivo e Binário são tipos de relacionamento'),
('bd', 'Qual simbolo é utilizado para indicar a operação de Seleção?', 'Alfa', 'Beta', 'Pi', 'Sigma', 'Sigma', 'O simbolo é utilizado para indicar a operação de Seleção é o Sigma.'),
('bd', 'Em Banco de dados relacionais a operação de JUNÇÃO:', 'É uma operação binária aplicada à três conjuntos de dados;', 'Cria uma nova tabela', 'Permite processar relacionamentos entre duas relações', 'Atualiza os atributos da tabela', 'Permite processar relacionamentos entre duas relações', 'O operador JOIN permite processar relacionamentos entre duas relações'),
('bd', 'Qual o comando em sql usado para excluir uma tabela?', 'ALTER', 'DROP', 'UPDATE', 'INSERT', 'DROP', 'Para excluir uma tabela em SQL, é utilizado o comando DROP.'),
('bd', 'Um cabeçalho da coluna é chamado de:', 'Atributo', 'Relação', 'Coluna', 'Tupla', 'Atributo', 'Um cabeçalho de uma coluna é chamado de atributo'),
('bd', 'A aridade de uma relação é o numero de ____ da relação:', 'Chaves', 'Tabelas', 'Atributos', 'Tuplas', 'Atributos', 'A aridade de uma relação é o número de atributos n dessa relação. Por exemplo, uma relação de grau 7, teria sete atributos.'),
('bd', 'Qual simbolo é utilizado para indicar a operação de Produto Cartesiano?', 'x', 'y', 'b', 'p', 'x', 'A operação de Produto Cartesiano é indicada por x');




INSERT INTO Questoes (materia, enunciado, alternativa_a, alternativa_b, alternativa_c, alternativa_d, resposta_correta, justificativa) VALUES
('lp', 'Qual é o valor da variável x após a execução do código: x = 5; x += 3; x *= 2;?', '10', '16', '19', '24', '16 ', 'Após a execução de "x = 5; x += 3; x *= 2;", o valor inicial de x é 5. Em seguida, ele é incrementado em 3, resultando em 8. Então, x é multiplicado por 2, resultando em 16. Portanto, o valor final de x é 16.'),
('lp', 'Em um laço de repetição do tipo while, qual é a condição para continuar executando o laço?', 'A condição é verificada antes de cada iteração.', 'A condição é verificada após cada iteração.', 'O laço é executado um número fixo de vezes.', 'O laço é executado infinitamente.', 'A condição é verificada antes de cada iteração.', ' A condição é verificada antes de cada iteração.'),
('lp', 'O que é um array em programação?', 'Uma estrutura de controle de seleção.', 'Um tipo de dado numérico.', 'Conjunto de elementos do mesmo tipo armazenados em sequência', 'Um operador lógico.', 'Conjunto de elementos do mesmo tipo armazenados em sequência', 'Conjunto de elementos do mesmo tipo armazenados em sequência.'),
('lp', 'O que é um algoritmo?', 'Uma sequência de ações para resolver um problema.', ' Um comando específico de uma linguagem de programação.', 'Uma variável de controle em um laço de repetição.', 'Uma estrutura de controle de seleção.', 'Uma sequência de ações para resolver um problema.', 'Um algoritmo é uma sequência de ações passo a passo para resolver um problema específico.'),
('lp', 'Qual é o operador usado para atribuição de valor a uma variável em programação?', '=', '==', '&&', '||', '=', 'O operador usado para atribuição de valor a uma variável em programação é o sinal de igual (=). Ele atribui o valor à variável à esquerda.'),
('lp', 'O que é um laço de repetição?', 'Executa um bloco de código até uma condição ser atendida.', 'Executa um bloco de código apenas uma vez.', 'Escolhe uma ação com base em condições específicas.', 'Verifica múltiplas condições e executa um bloco de código.', 'Executa um bloco de código até uma condição ser atendida.', 'Um laço de repetição executa um bloco de código repetidamente até que uma condição seja atendida, permitindo automatizar tarefas repetitivas e iterar sobre dados até que uma condição de parada seja alcançada.'),
('lp', 'Qual é o resultado da expressão 10 % 3?', '1', '2', '3', '4', '1', 'O operador de módulo (%) retorna o resto da divisão de 10 por 3, que é igual a 1.'),
('lp', 'Qual é o valor de i após a execução do código: int i = 5; i++; ++i;?', '5', '6', '7', '8', '8', 'A operação "i++" incrementa o valor atual de i em 1, e a operação "++i" pré-incrementa o valor de i em 1. Portanto, o valor final de i é 8.'),
('lp', 'O que é um operador ternário em programação?', 'Um operador que combina dois valores lógicos.', 'Um operador que realiza operações matemáticas.', 'Um operador que compara dois valores.', 'Um operador condicional com três operandos.', 'Um operador condicional com três operandos.', 'O operador ternário, representado por "? :", é um operador condicional que possui três operandos e retorna um valor com base em uma condição.'),
('lp', 'Qual é o operador lógico usado para negação?', '&& ', '||', '!', '^', '!', 'O operador de negação lógica (!) inverte o valor de uma expressão booleana, transformando verdadeiro em falso e falso em verdadeiro.'),
('lp', 'Qual é a finalidade do operador de incremento "++"?', 'Multiplicar um valor por 2.', 'Dividir um valor por 2.', 'Adicionar 1 a um valor.', 'Subtrair 1 de um valor.', 'Adicionar 1 a um valor.', 'O operador de incremento "++" adiciona 1 ao valor atual de uma variável.'),
('lp', 'O que é um operador de concatenação de strings?', 'Um operador que realiza operações matemáticas com strings.', 'Um operador que une duas ou mais strings em uma única string', 'Um operador que compara duas strings e retorna um booleano.', 'Um operador que extrai uma substring de uma string.', 'Um operador que une duas ou mais strings em uma única string', 'Um operador de concatenação de strings é usado para unir duas ou mais strings em uma única string.'),
('lp', 'São tipos de estruturas de controle de seleção utilizadas na construção de algoritmos, EXCETO:', 'Sequencial.', 'Encadeada.', 'Simples.', 'Múltipla escolha.', 'Simples', ' A estrutura simples envolve uma única instrução condicional (if-then) (if-then-else). Se a condição especificada for verdadeira, a instrução dentro da estrutura é executada; caso contrário, ela é ignorada.'),
('lp', 'Qual é o resultado da expressão 2 + 3 * 4 / 2?', '8', '9', '10', '11', '10', ' A expressão segue a ordem de precedência dos operadores matemáticos, então a multiplicação e a divisão são feitas antes da adição.'),
('lp', 'Na linguagem Python, um exemplo de comando para criar uma condição:', 'If', 'For', 'While', 'Do', 'If', 'Na linguagem Python, os comandos utilizados para criar uma condição são: if, else, elif, no exemplo acima o utilizado foi If.'),
('lp', 'Na linguagem Python, qual é a sintaxe correta para criar uma lista em Python?', 'c = list(1, 2, 3)', 'c = [1, 2, 3]', 'c = 1, 2, 3', 'c = list[1, 2, 3]', 'c = [1, 2, 3]', 'Na linguagem Python, as listas são criadas usando colchetes e separando os elementos por vírgulas.'),
('lp', 'Na linguagem Python, a sequência imutável de valores de qualquer tipo é conhecida como:', 'Tupla', 'Dicionario', 'Lista', 'Break', 'Tupla', 'Na linguagem Python, a sequência imutável de valores de qualquer tipo é conhecida como tupla.'),
('lp', 'Na linguagem Python, qual comando/função é utilizado para descobrir o tamanho de uma lista?', 'def', '.sort', '.append', 'len()', 'len()', 'Na linguagem Python, a função utilizada para descobrir o tamanho da lista é len(), ela retorna o número de elementos na lista.'),
('lp', 'Na linguagem Python, qual destes comandos pode ser utilizado para formar um loop:', 'math', 'for', 'zip', 'sort', 'for', 'Na linguagem Python, para se criar um loop podem ser utilizados os comandos: for, while, do/while, no exemplo acima o utilizado foi o for.'),
('lp', 'Na linguagem Python, o comando livros = {} cria um:', 'Classe', 'Dicionário', 'Tupla', 'Lista', 'Dicionário', 'Na linguagem Python, para se criar um dicionário utilizasse {}, no exemplo acima seria criado um dicionário vazio chamado livros.'),
('lp', 'Na linguagem Python, qual é a função do comando print()?', 'Combinar registros de duas ou mais tabelas', 'Somar os valores de uma lista', 'Exibir mensagens na tela', 'Ordenar uma lista', 'Exibir mensagens na tela', 'Na linguagem Python, a função do comando print() é exibir mensagens na tela ou em outro dispositivo de saída.'),
('lp', 'Na linguagem Python, qual é a função do comando input()?', 'Exibir mensagens na tela', 'Realizar a leitura de dados inseridos pelo usuário', 'Converter um valor para string', 'Verificar a existência de um elemento em uma lista', 'Realizar a leitura de dados inseridos pelo usuário', 'Na linguagem Python, o comando input() é utilizado para realizar a leitura de dados inseridos pelo usuário.'),
('lp', 'O que o código a = float(input(\'Digite\')) print(solicita ao usuário?', 'Número', 'Float', 'Palavra', 'Inteiro', 'Float', 'O código solicita ao usuário um número do tipo float.'),
('lp', 'O código L = [] for x in range(8, 2, -1): L.append(x) print(L) exibe a lista:', '[8, 7, 6, 5, 4, 3]', '[3, 4, 5, 6, 7, 8]', '[4, 6, 5, 3, 7, 8]', '[8, 5, 6, 3, 7, 4]', '[8, 7, 6, 5, 4, 3]', 'A função range gera uma sequência de números de 8 a 2 (decrementando -1 a cada iteração), resultando na lista [8, 7, 6, 5, 4, 3].'),
('lp', 'Qual não é um tipo de dado em Python?', 'Int', 'Char', 'Float', 'Str', 'Char', 'Entre as opções, \'Char\' não é um tipo de dado em Python.'),
('lp', 'O código a = int(input(\'Digite\')) print(exibe na tela:', 'Número aleatório', 'Número digitado pelo usuário', 'Lista', 'Frase', 'Número digitado pelo usuário', 'O código solicita ao usuário um número inteiro, que é exibido na tela.'),
('lp', 'Qual função em Python combina iteráveis em um iterável de tuplas?', 'Append', 'Insert', 'Len', 'Zip', 'Zip', 'A função \'zip\' combina iteráveis em um iterável de tuplas.');

INSERT INTO questoes (materia, enunciado, alternativa_a, alternativa_b, alternativa_c, alternativa_d, resposta_correta, justificativa) VALUES
('moo', 'As interações do Diagrama de Classe da UML podem ser:', 'Auxiliares e Usuais', 'Funcionais e Não Funcionais', 'Bidirecional e Unidirecional', 'Lateral e Unilateral', 'Bidirecional e Unidirecional', 'Em Modelagem Orientada ao Objeto, as interações do Diagrama de Classe da UML podem ser Bidirecional ou Unidirecional.'),
('moo', 'O que é um atributo em um diagrama de classes?', 'Uma ação realizada por um objeto em um sistema.', 'Uma característica de um objeto em um sistema.', 'Uma interação entre objetos em um sistema.', 'Um relacionamento entre classes em um sistema.', 'Uma característica de um objeto em um sistema.', 'Um atributo é uma característica de um objeto que descreve seu estado ou características distintas.'),
('moo', 'O que é uma classe abstrata em programação orientada a objetos?', 'Uma classe que não pode ser instanciada.', 'Uma classe que herda atributos e métodos de outras classes.', 'Uma classe que define a estrutura de objetos', 'Uma classe que é herdada por outras classes.', 'Uma classe que não pode ser instanciada.', 'Uma classe abstrata é uma classe que não pode ser instanciada diretamente, mas pode ser usada como base para outras classes através de herança.'),
('moo', 'O que é uma classe concreta em programação orientada a objetos?', 'Uma classe que pode ser instanciada diretamente.', 'Uma classe que herda atributos e métodos de outras classes.', 'Uma classe que define a estrutura de objetos', 'Uma classe que não pode ser herdada por outras classes.', 'Uma classe que pode ser instanciada diretamente.', 'Uma classe concreta é uma classe que pode ser instanciada diretamente para criar objetos. É uma classe que não é abstrata e não precisa ser herdada antes de ser utilizada para criar objetos.'),
('moo', 'Quais são os dois principais tipos de diagramas de interação utilizados na modelagem de sistemas?', 'Diagrama de atividades e diagrama de colaboração.', 'Diagrama de classes e diagrama de sequência.', 'Diagrama de estado e diagrama de objetos.', ' Diagrama de sequência e diagrama de comunicação.', 'Diagrama de sequência e diagrama de comunicação', 'Diagrama de sequência:  foca na representação da ordem temporal das mensagens trocadas entre os objetos. Diagrama de comunicação:  destaca as interações entre os objetos, mostrando a estrutura e as relações'),
('moo', 'No diagrama de Máquina de Estado, o que representa o sincronismo?', 'A sequência exata das mensagens trocadas entre os objetos.', 'A sincronização de operações simultâneas entre os objetos.', 'A definição das responsabilidades dos atores envolvidos.', ' O fluxo de controle entre os estados de um objeto.', 'A sincronização de operações simultâneas entre os objetos ', 'O sincronismo indica momentos em que diferentes objetos estão envolvidos em ações coordenadas ou dependem um do outro para avançar em suas operações.'),
('moo', 'No diagrama de classes, qual é a finalidade da multiplicidade em associações entre classes?', 'Representar a cardinalidade das classes envolvidas.', ' Indicar a visibilidade dos atributos nas classes.', 'Estabelecer a ordem de execução dos métodos nas classes.', ' Mostrar a hierarquia de herança entre as classes.', 'Representar a cardinalidade das classes envolvidas', 'A multiplicidade indica quantas instâncias de uma classe estão relacionadas com instâncias da outra classe.'),
('moo', 'No diagrama de classes, o que as associações representam entre as classes?', 'Atributos compartilhados entre as classes.', 'Métodos comuns entre as classes.', 'Relacionamentos e interações entre as classes.', ' Dependências de implementação entre as classes.', 'Relacionamentos e interações entre as classes', 'As associações no diagrama de classes representam os relacionamentos e interações entre as classes do sistema modelado. Elas mostram como as classes estão conectadas e se relacionam umas com as outras.'),
('moo', 'Na moo, qual é o princípio que incentiva a divisão de responsabilidades entre as classes?', ' Encapsulamento', 'Herança', ' Polimorfismo', ' Coesão', 'Coesão', 'Uma classe coesa é aquela que possui uma única responsabilidade bem definida e desempenha um papel específico dentro do sistema'),
('moo', 'Qual é o objetivo principal da herança na Modelagem Orientada a Objetos?', 'Permitir a reutilização de código.', 'Estabelecer relacionamentos entre classes.', 'Definir atributos e comportamentos de objetos.', 'Facilitar a comunicação entre objetos.', 'Permitir a reutilização de código.', ' Herança na Modelagem Orientada a Objetos permite a reutilização de código com base em classes existentes. Através da herança, as subclasses herdam os atributos e métodos da classe base.'),
('moo', 'Qual é a finalidade do diagrama de máquina de estados?', 'Representar o fluxo de controle de um sistema.', 'Descrever a estrutura interna dos objetos.', ' Mostrar a interação entre atores e casos de uso.', 'Indicar a sequência de mensagens entre objetos.', 'Representar o fluxo de controle de um sistema.', 'O diagrama de máquina de estados é usado para representar o comportamento de um objeto ou sistema, focando no fluxo de controle e nas transições de estados.'),
('moo', 'No diagrama de sequência, qual é a finalidade do fluxo de mensagens?', 'Representar a troca de informações entre objetos.', 'Descrever a ordem de execução dos métodos.', ' Mostrar a estrutura interna dos objetos.', ' Indicar os atributos dos objetos.', 'Representar a troca de informações entre objetos', 'O fluxo de mensagens no diagrama de sequência é utilizado para representar a comunicação e a troca de informações entre os objetos envolvidos em um determinado cenário.'),
('moo', 'O diagrama de caso de uso é uma ferramenta fundamental para a análise de requisitos. No contexto de diagrama de caso de uso, qual é a finalidade do ator?', ' Executar uma ação específica no sistema.', 'Representar um objeto do mundo real.', ' Interagir com o sistema em algum papel.', ' Definir um conjunto de casos de uso.', 'Interagir com o sistema em algum papel.', 'No diagrama de caso de uso, o ator representa um agente externo, como um usuário, um sistema externo ou outro sistema. Ele interage com o sistema em algum papel específico'),
('moo', 'Em Modelagem Orientada ao Objeto, quais são os principais Tipos de Requisitos?', 'Requisitos Funcionais e Não Funcionais', 'Requisitos Tecnicos e Requisitos de Sistema', 'Requisitos Auxiliares e Cardinais', 'Requisitos Usuais e Nao usuais', 'Requisitos Funcionais e Não Funcionais', 'Em Modelagem Orientada ao Objeto, os principais tipos de requisitos são: Requisitos Funcionais e Não Funcionais.'),
('moo', 'Qual é o conceito que define a capacidade de um objeto assumir diferentes formas?', 'Encapsulamento', 'Herança', 'Polimorfismo', 'Abstração', 'Polimorfismo', 'Polimorfismo é o conceito que permite que um objeto possa ser referenciado de várias formas, dependendo do contexto.'),
('moo', 'Quais são os Diagramas UML 2.5?', 'Diagramas Estruturais e Comportamentais', 'Diagramas de pacotes e objetos', 'Diagramas de sequencia e máquina de estado', 'Diagramas de componentes e implantação', 'Diagramas Estruturais e Comportamentais', 'Apenas os diagramas Estruturais e Comportamentais dentre as opções fazem parte da UML 2.5.'),
('moo', 'São exemplos de diagramas:', 'Espiral e Conceitual', 'Computacional e Relacional', 'Classe e Objeto', 'Máquina de estado e Operacional', 'Classe e Objeto', 'A única alternativa que contém 2 exemplos de diagramas é "Classe e Objeto".'),
('moo', 'Os escopos para os membros do Diagrama de Classe da UML são:', 'Classificadores e Instâncias', 'Objetivos e Classificadores', 'Construtores e Instâncias', 'Objetivos e Construtores', 'Classificadores e Instâncias', 'São membros estáticos e instâncias específicas da classe.'),
('moo', 'As interações do Diagrama de Classe da UML podem ser:', 'Auxiliares e Usuais', 'Funcionais e Não Funcionais', 'Bidirecional e Unidirecional', 'Lateral e Unilateral', 'Bidirecional e Unidirecional', 'Em Modelagem Orientada ao Objeto, as interações do Diagrama de Classe da UML podem ser Bidirecional ou Unidirecional.'),
('moo', 'No diagrama de estado, o que representa um estado final?', 'objeto passa do estado anterior para o próximo estado', 'estado de um objeto quando ele é criado.', 'Estado intermediário', ' fim do ciclo de vida de um objeto', 'fim do ciclo de vida de um objeto', 'O estado final indica o término do processo ou entidade.'),
('moo', 'Qual o objetivo principal do diagrama de classe?', 'Representar a interação entre objetos', 'Ilustrar o fluxo de controle do sistema', 'Descrever a estrutura e relacionamentos das classes', 'Mostrar a sequência de eventos em um processo', 'Descrever a estrutura e relacionamentos das classes', 'O diagrama de classe descreve a estrutura das classes e seus relacionamentos.'),
('moo', 'No diagrama de sequência, o que representa uma mensagem assíncrona?', 'Mensagem com retorno', 'Mensagem entre objetos distintos', 'Mensagem que espera resposta', 'Mensagem enviada simultaneamente por todos os objetos', 'Mensagem entre objetos distintos', 'Uma mensagem assíncrona ocorre entre objetos diferentes e não requer resposta imediata.'),
('moo', 'No contexto do diagrama de objeto, o que é uma instância?', 'Método de uma classe', 'Variável de classe', 'Objeto específico de uma classe', 'Atributo compartilhado entre várias instâncias', 'Objeto específico de uma classe', 'Uma instância é um objeto específico criado a partir de uma classe.'),
('moo', 'No diagrama de estado, o que representa uma transição de auto-loop?', 'Mudança de estado para um estado final', 'Mudança de estado para um estado intermediário', 'Mudança de estado para um estado inicial', 'Mudança de estado para o próprio estado', 'Mudança de estado para o próprio estado', 'Uma transição de auto-loop indica a mudança de estado para o estado em que o objeto já se encontra.'),
('moo', 'O que é representado pelo símbolo de sinal de mais (+) em um diagrama de classe?', 'Atributo público', 'Método público', 'Atributo privado', 'Método privado', 'Atributo público', 'O símbolo de sinal de mais (+) indica um atributo público em um diagrama de classe.'),
('moo', 'Qual é o objetivo principal do diagrama de sequência?', 'Descrever a estrutura de uma classe e seus métodos', 'Representar o fluxo de controle e as decisões do sistema', 'Mostrar interação entre objetos em um período', 'Mostrar as mudanças de estado de um objeto', 'Mostrar a interação entre objetos em um período', 'O diagrama de sequência mostra a interação entre objetos em um determinado período.'),
('moo', 'O que é uma supertransição em um diagrama de estado?', 'Uma transição entre estados finais', 'Uma transição entre estados iniciais', 'Uma transição entre estados intermediários', 'Uma transição que inclui várias transições', 'Uma transição que inclui várias transições', 'Uma supertransição é uma transição que inclui várias transições menores dentro de um diagrama de estado.'),
('moo', 'Qual é o propósito do diagrama de classe?', 'Descrever o fluxo de controle e as atividades do sistema', 'Representar a interação entre objetos em um período', 'Mostrar a estrutura e relacionamentos das classes', 'Ilustrar as mudanças de estado de um objeto', 'Mostrar a estrutura e relacionamentos das classes', 'O diagrama de classe mostra a estrutura das classes e seus relacionamentos, fornecendo uma visão estática do sistema.'),
('moo', 'O que é uma mensagem de retorno em um diagrama de sequência?', 'Mensagem que aguarda uma resposta', 'Mensagem enviada por todos os objetos simultaneamente', 'Mensagem com conteúdo de retorno', 'Mensagem entre objetos distintos', 'Mensagem com conteúdo de retorno', 'Uma mensagem de retorno em um diagrama de sequência é uma mensagem que traz consigo um conteúdo de retorno associado.'),
('moo', 'No contexto do diagrama de objeto, o que é um método?', 'Atributo de uma classe', 'Objeto específico de uma classe', 'Variável de classe', 'Comportamento ou ação de uma classe', 'Comportamento ou ação de uma classe', 'Um método em um diagrama de objeto representa o comportamento ou ação específica de uma classe.'),
('moo', 'O que é uma região em um diagrama de estado?', 'Uma subdivisão de um estado', 'Um estado inicial', 'Um estado intermediário', 'Um estado final', 'Uma subdivisão de um estado', 'Uma região é uma subdivisão de um estado em um diagrama de estado, permitindo representar diferentes subestados e transições internas.'),
('moo', 'O que é um relacionamento de agregação em um diagrama de classe?', 'Relacionamento entre classes onde a classe é parte de outra', 'Relacionamento entre classes em que uma classe possui outra', 'Relacionamento entre classes onde uma classe herda de outra', 'Relacionamento entre classes onde uma classe é igual a outra', 'Relacionamento entre classes onde uma classe possui outra', 'Um relacionamento de agregação em um diagrama de classe indica que uma classe possui outra classe.'),
('moo', 'O que é uma mensagem síncrona em um diagrama de sequência?', 'Mensagem entre objetos distintos', 'Mensagem que espera uma resposta', 'Mensagem enviada simultaneamente por todos os objetos', 'Mensagem com conteúdo de retorno', 'Mensagem que espera uma resposta', 'Uma mensagem síncrona em um diagrama de sequência é uma mensagem que aguarda uma resposta antes de prosseguir.'),
('moo', 'O que é um atributo em um diagrama de objeto?', 'Comportamento ou ação de uma classe', 'Variável de classe', 'Objeto específico de uma classe', 'Relacionamento entre classes', 'Variável de classe', 'Um atributo em um diagrama de objeto representa uma variável associada a uma classe.'),
('moo', 'O que é uma ação em um diagrama de estado?', 'Mudança de estado de um objeto', 'Evento que dispara uma transição', 'Subdivisão de um estado', 'Comportamento executado por um objeto', 'Comportamento executado por um objeto', 'Uma ação em um diagrama de estado representa um comportamento ou uma ação executada por um objeto em um estado específico.'),
('moo', 'O que é uma herança em um diagrama de classe?', 'Relacionamento entre classes onde uma é parte outra', 'Relacionamento entre classes em que uma classe possui outra', 'Relacionamento entre classes onde uma classe herda de outra', 'Relacionamento entre classes onde uma classe é igual a outra', 'Relacionamento entre classes onde uma classe herda outra', 'A herança em um diagrama de classe indica que uma classe herda características e comportamentos de outra classe.'),
('moo', 'O que é uma mensagem assíncrona em um diagrama de sequência?', 'Mensagem entre objetos distintos', 'Mensagem com conteúdo de retorno', 'Mensagem que aguarda uma resposta', 'Mensagem enviada simultaneamente por todos os objetos', 'Mensagem entre objetos distintos', 'Uma mensagem assíncrona em um diagrama de sequência ocorre entre objetos distintos e não requer resposta imediata.'),
('moo', 'O que é uma classe em um diagrama de objeto?', 'Comportamento ou ação de uma classe', 'Variável de classe', 'Objeto específico de uma classe', 'Descrição de um tipo de objeto', 'Descrição de um tipo de objeto', 'Uma classe em um diagrama de objeto representa a descrição de um tipo de objeto, especificando os atributos e comportamentos que os objetos desse tipo possuem.'),
('moo', 'O que é uma guarda em um diagrama de estado?', 'Condição que deve ser satisfeita para a transição ocorrer', 'Evento que dispara uma transição', 'Subdivisão de um estado', 'Comportamento executado por um objeto', 'Condição que deve ser satisfeita para a transição ocorrer', 'Uma guarda em um diagrama de estado é uma condição que deve ser satisfeita para que a transição ocorra.'),
('moo', 'O que é um relacionamento de composição em um diagrama de classe?', 'Relação entre classes onde a classe é parte de outra', 'Relacionamento entre classes em que uma classe possui outra', 'Relacionamento entre classes onde uma classe herda de outra', 'Relacionamento entre classes onde uma classe é igual a outra', 'Relação entre classes onde a classe é parte de outra', 'Um relacionamento de composição em um diagrama de classe indica que uma classe é composta por outra classe.'),
('moo', 'O que é um objeto em um diagrama de sequência?', 'Comportamento ou ação de uma classe', 'Variável de classe', 'Instância de uma classe', 'Relacionamento entre classes', 'Instância de uma classe', 'Um objeto em um diagrama de sequência representa uma instância específica de uma classe, que está envolvida na interação com outros objetos.');
  

INSERT INTO questoes (materia, enunciado, alternativa_a, alternativa_b, alternativa_c, alternativa_d, resposta_correta, justificativa) VALUES
('poo', 'O que é herança múltipla?', ' A classe poder herdar atributos de várias classes', 'capacidade de uma classe herdar atributos de uma só classe', 'Um relacionamento onde uma classe referencia outra classe', 'A capacidade do objeto se comportar de maneira polivalente', 'A classe poder herdar características de várias classes', 'A herança múltipla em Programação Orientada a Objetos é a capacidade de uma classe herdar características (atributos e métodos) de várias classes, permitindo uma maior flexibilidade e reutilização de código.'),
('poo', 'O que é sobrescrita de métodos?', 'Relação onde a classe herda atributos de várias classes', 'A capacidade da classe herdar atributos de uma única classe', 'Relação onde uma classe tem uma referência a outra classe', 'Alterar a implementação de um método na classe filha', 'Alterar a implementação de um método na classe filha', 'A sobrescrita de métodos em Programação Orientada a Objetos ocorre quando uma classe filha altera a implementação de um método herdado da classe pai, adequando-o às suas necessidades específicas.'),
('poo', 'O que é uma superclasse em Java?', 'Uma função específica que realiza uma tarefa', 'Um local onde são declaradas variáveis', 'Uma classe que contém apenas métodos abstratos', 'Uma classe da qual outras classes herdam características', 'Uma classe da qual outras classes herdam características', 'Uma superclasse em Java é uma classe da qual outras classes herdam características, sendo a base para a criação de outras classes.'),
('poo', 'O que é polimorfismo de herança?', 'Um tipo de relacionamento entre classes', 'A classe poder herdar atributos de várias classes', 'A classe poder herdar atributos de uma única classe', 'Um objeto que pode se comportar de maneira polivalente', 'A classe poder herdar atributos de uma única classe', 'O polimorfismo de herança em POO ocorre quando a classe herda atributos e métodos de uma só classe, mas pode ser usada de forma polivalente, podendo se comportar como sua classe pai ou como sua própria classe.'),
('poo', 'Qual é o conceito central da Programação Orientada a Objetos?', 'Herança', 'Polimorfismo', 'Encapsulamento', 'Abstração', 'Encapsulamento', 'O encapsulamento é o conceito central da Programação Orientada a Objetos, pois permite ocultar os detalhes internos de uma classe e expor apenas sua interface de uso.'),
('poo', 'O que é polimorfismo em POO?', 'Um tipo de relacionamento entre classes', 'A classe poder herdar características de várias classes', 'Uma relação onde uma classe tem referência a outra classe', 'Um objeto poder se comportar de maneira polivalente', 'Um objeto poder se comportar de maneira polivalente', 'O polimorfismo em Programação Orientada a Objetos permite que um objeto possa se comportar de maneira polivalente, ou seja, adotar diferentes comportamentos dependendo do contexto.'),
('poo', 'O que é um construtor em POO?', 'Um método que retorna um valor específico', 'Um método que destrói um objeto', 'Um método que cria e inicializa um objeto', 'Um método que imprime informações na tela', 'Um método que cria e inicializa um objeto', 'Um construtor em Programação Orientada a Objetos é um método especial utilizado para criar e inicializar objetos quando uma instância da classe é criada.'),
('poo', 'O que são atributos em POO?', 'Métodos que retornam valores específicos', 'Variáveis que armazenam valores específicos', 'Classes que contêm apenas métodos', 'Interfaces que definem um contrato para uma classe', 'Variáveis que armazenam valores específicos', 'Atributos em Programação Orientada a Objetos são variáveis que armazenam valores específicos relacionados a um objeto.'),
('poo', 'O que são modificadores de acesso em Java?', 'Palavras-chave que controlam o acesso a valores da classe', 'Palavras-chave usadas para declarar variáveis', 'Palavras-chave usadas para definir comportamentos de objetos', 'Palavras-chave usadas para estruturar o código em blocos', 'Palavras-chave que controlam o acesso a valores da classe', 'Os modificadores de acesso em Java são palavras-chave usadas para controlar o acesso a classes, atributos e métodos, determinando quem pode acessá-los.'),
('poo', 'O que é um método getter em Java?', 'Um método que retorna um valor específico', 'Um método que destrói um objeto', 'Um método que cria e inicializa um objeto', 'Um método que imprime informações na tela', 'Um método que retorna um valor específico', 'Um método getter em Java é um método utilizado para acessar e retornar o valor de um atributo privado de uma classe.'),
('poo', 'O que é um método setter em Java?', 'Um método que retorna um valor específico', 'Um método que destrói um objeto', 'Um método que cria e inicializa um objeto', 'Um método que modifica o valor de um atributo', 'Um método que modifica o valor de um atributo', 'Um método setter em Java é um método utilizado para modificar o valor de um atributo privado de uma classe.'),
('poo', 'O que é uma interface em Java?', 'Uma função específica que realiza uma tarefa', 'Um local onde são declaradas variáveis', 'Uma classe que contém apenas métodos abstratos', 'Um modelo ou plano para criar objetos específicos', 'Uma classe que contém apenas métodos abstratos', 'Uma interface em Java é uma classe que contém apenas métodos abstratos, ou seja, métodos sem implementação.'),
('poo', 'O que é polimorfismo de sobrecarga?', 'Relação que a classe herda características de várias classes', 'Relação que a classe herda atributos de uma única classe', 'Relação onde uma classe herda atributos de classes abstratas', 'Ter métodos com o mesmo nome, mas com diferentes parâmetros', 'Ter métodos com o mesmo nome e com diferentes parâmetros', 'O polimorfismo de sobrecarga ocorre quando uma classe possui métodos com o mesmo nome, porém com diferentes parâmetros, permitindo que sejam chamados de acordo com o tipo e quantidade de argumentos passados.'),
('poo', 'O que é uma classe abstrata em Java?', 'Uma função específica que realiza uma tarefa', 'Um local onde são declaradas variáveis', 'Uma classe que contém apenas métodos abstratos', 'Classe não instanciável usada como base de outras classes', 'Classe não instanciável usada como base de outras classes', 'Uma classe abstrata em Java é uma classe que não pode ser instanciada, ou seja, não pode ser usada diretamente para criar objetos, mas pode ser usada como base para outras classes.'),
('poo', 'O que é herança em Programação Orientada a Objetos?', 'Um tipo de relacionamento entre classes', 'A classe poder herdar características de várias classes', 'Relação onde uma classe tem uma referência a outra classe', 'Um objeto poder se comportar de maneira polivalente', 'A classe poder herdar características de várias classes', 'A herança em Programação Orientada a Objetos permite que uma classe herde características (atributos e métodos) de outra classe, possibilitando a reutilização de código e a criação de uma hierarquia de classes.'),
('poo', 'O que é encapsulamento em POO?', 'Relação onde uma classe herda atributos de várias classes', ' A classe poder herdar características de uma única classe', 'Relação onde uma classe tem uma referência a outra classe', 'Ocultar detalhes de uma classe e expor sua interface só', 'Ocultar detalhes de uma classe e expor sua interface só', 'O encapsulamento em POO consiste em ocultar os detalhes internos de uma classe e expor apenas sua interface de uso, protegendo os atributos e permitindo o acesso controlado através de métodos.'),
('poo', 'O que é composição em POO?', 'Um tipo de relacionamento entre classes', 'A classe poder herdar características de várias classes', 'Relação onde uma classe tem referência a outra classe', 'O objeto poder se comportar de maneira polivalente', 'Relação onde uma classe tem referência a outra classe', 'A composição em Programação Orientada a Objetos é um tipo de relacionamento onde uma classe tem uma referência a outra classe e é composta por ela.'),
('poo', 'O que é herança múltipla?', 'A classe poder herdar características de várias classes', 'A classe poder herdar características de uma única classe', 'Relação onde uma classe tem uma referência a outra classe', 'O objeto poder se comportar de maneira polivalente', 'A classe poder herdar características de várias classes', 'A herança múltipla em Programação Orientada a Objetos é a capacidade de uma classe herdar características (atributos e métodos) de várias classes, permitindo uma maior flexibilidade e reutilização de código.'),
('poo', 'O que é sobrescrita de métodos?', 'Relação onde uma classe herda atributos de várias classes', 'A classe poder herdar características de uma única classe', 'Relação onde uma classe tem uma referência a outra classe', 'Alterar a implementação de um método na classe filha', 'Alterar a implementação de um método na classe filha', 'A sobrescrita de métodos em Programação Orientada a Objetos ocorre quando uma classe filha altera a implementação de um método herdado da classe pai, adequando-o às suas necessidades específicas.'),
('poo', 'O que é uma superclasse em Java?', 'Uma função específica que realiza uma tarefa', 'Um local onde são declaradas variáveis', 'Uma classe que contém apenas métodos abstratos', 'Uma classe da qual outras classes herdam características', 'Uma classe da qual outras classes herdam características', 'Uma superclasse em Java é uma classe da qual outras classes herdam características, sendo a base para a criação de outras classes.'),
('poo', 'Qual não é um tipo de dado primitivo?', 'Int', 'Char', 'String', 'Booleano', 'String', 'Em POO, todas as opções são tipos primitivos, exceto a String.'),
('poo', 'Qual comando aloca memória para um objeto recém-criado?', 'Memory', 'New', 'Address', 'Store', 'New', 'Em POO, o comando \'new\' aloca memória para um objeto recém-criado.'),
('poo', 'Qual não é um princípio da POO?', 'Recursão', 'Encapsulamento', 'Abstração', 'Herança', 'Recursão', 'Recursão não é um princípio da POO.'),
('poo', 'Qual é uma instrução de looping?', 'switch', 'void', 'public', 'while', 'while', 'Em POO, \'while\' é uma instrução de looping.'),
('poo', 'Qual indica um modificador de acesso?', 'for', 'static', 'public', 'final', 'public', 'Em POO, \'public\' é um modificador de acesso.'),
('poo', 'Qual termina um loop?', 'catch', 'for', 'break', 'void', 'break', 'Em POO, \'break\' termina um loop.'),
('poo', 'Qual tipo de loop é um loop de pós-teste?', 'do-while', 'while', 'forEach', 'for', 'do-while', 'Em POO, o loop de pós-teste é \'do-while\'.'),
('poo', 'Qual não é uma classe wrapper?', 'Booleano', 'String', 'Byte', 'Valor inteiro', 'String', 'Em POO, \'String\' não é uma classe wrapper.'),
('poo', 'Qual não é um operador lógico?', '^^', '!', '&&', '||', '^^', 'Em POO, \'^^\' não é um operador lógico.'),
('poo', 'Qual operador concatena Strings?', '=', '&', '.', '+', '+', 'Em Java, o operador \'+\' concatena Strings.'),
('poo', 'O que é uma classe em Java?', 'Uma função específica que realiza uma tarefa.', 'Um local onde são declaradas variáveis.', 'Um bloco de código que é executado várias vezes.', 'Um modelo ou plano para criar objetos específicos.', 'Um modelo ou plano para criar objetos específicos.', 'Uma classe em Java é um modelo ou plano para criar objetos específicos.'),
('poo', 'Qual é a finalidade dos métodos getter e setter em uma classe Java?', 'Manipular os atributos da classe.', 'Definir o comportamento da classe.', 'Permitir a criação de objetos.', 'Controlar o fluxo de execução do programa.', 'Manipular os atributos da classe.', 'Os métodos getter e setter em uma classe Java são utilizados para manipular os atributos da classe.');
